apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-frontend
  template:
    metadata:
      labels:
        app: crud-frontend
    spec:
      containers:
        - name: crud-frontend
          image: xhawk1337/crud-react-app:1.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
