apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd/namespace.yaml
  - ./argocd/ingress.yaml
  - ./argocd/application.yaml
  - ./rbac/pod-lister-role.yaml
  - ./namespaces/development.yaml
  - ./frontend/service.yaml
  - ./frontend/fronted-deployment.yaml
  - ./ingress/ingress-nginx.yaml
  - ./database/postgres-deployment.yaml
  - ./database/service.yaml
  - ./database/postgres-config.yaml
  - ./database/postgres-secret.yaml
  - ./database/postgres-pvc.yaml
  - ./backend/service.yaml
  - ./backend/backend-deployment.yaml
